# Generated by Django 4.2 on 2025-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Dificultad',
                'verbose_name_plural': 'Dificultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Duración',
                'verbose_name_plural': 'Duraciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MomentoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Momento de clase',
                'verbose_name_plural': 'Momentos de clase',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pensamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Pensamiento',
                'verbose_name_plural': 'Pensamientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoAgrupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de agrupación',
                'verbose_name_plural': 'Tipos de agrupación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('explicacion', models.TextField(help_text='Cómo funciona la técnica')),
                ('link_externo', models.URLField(blank=True, help_text='URL de referencia', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('agrupaciones', models.ManyToManyField(related_name='tecnicas', to='tecnicas.tipoagrupacion')),
                ('carreras', models.ManyToManyField(related_name='tecnicas', to='tecnicas.carrera')),
                ('dificultades', models.ManyToManyField(related_name='tecnicas', to='tecnicas.dificultad')),
                ('duraciones', models.ManyToManyField(related_name='tecnicas', to='tecnicas.duracion')),
                ('momentos', models.ManyToManyField(related_name='tecnicas', to='tecnicas.momentoclase')),
                ('pensamientos', models.ManyToManyField(related_name='tecnicas', to='tecnicas.pensamiento')),
            ],
        ),
    ]
