# Generated by Django 4.2 on 2025-06-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dificultad',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
