# Generated by Django 4.2 on 2025-06-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0002_dificultad_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='duracion',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='momentoclase',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
